add az

diff --git a/.github/workflows/build-and-push.yml b/.github/workflows/build-and-push.yml
--- a/.github/workflows/build-and-push.yml
+++ b/.github/workflows/build-and-push.yml
@@ -55,13 +55,10 @@ jobs:
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan -H 13.69.215.70 >> ~/.ssh/known_hosts
 
-      - name: SSH to VM and Install Docker
+      - name: SSH to VM and Install Docker and Az CLI
         run: |
           ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no tung@13.69.215.70 << 'EOF'
             echo "Connected to VM successfully!"
-
-            echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_creds.json
-            az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"
             
             # Update package list and install Docker if not already installed
             if ! command -v docker &> /dev/null; then
@@ -75,6 +72,18 @@ jobs:
             else
               echo "Docker is already installed."
             fi
+
+            # Install Azure CLI if not already installed
+            if ! command -v az &> /dev/null; then
+              echo "Azure CLI not found, installing..."
+              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+            else
+              echo "Azure CLI is already installed."
+            fi
+
+            # Connect to Azure using service principal
+            echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_creds.json
+            az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"
 
             # Pull the Docker image from ACR
             az acr login --name ${{ env.ACR_NAME }}
